### ISSUE TITLE
After pluing installation on 3.2.0 - Error 500 when displaying some issues

### ISSUE THREAD

**Issue by DanyK7** [staskie/simple_author_change#12]
We just installed this plugin on bitnami-redmine version 3.2.0 (see below for RAIL env)
We activated the module and could change the author of a ticket as expected.
It installed well and all seemed to work, so we moved to it to our "prod" environment, a little too fast.

We then realize that when we couldnt display some tickets, getting error 500.
Other ticket would work some wouldnt, even for admins.

We are not able to identify a pattern why some ticket do work well and some others get the 500 errors.
We disabled the plugin in our project, same problem on same tickets.

Can anyone help ?
Is there an uninstall procedure ?

The logs do contain this error message everytime we have the 500 error.
Started GET "/redmine/issues/150" for 10.177.100.69 at 2016-01-29 14:27:51 +0000
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"150"}
  Current user: fxxxxxx (id=11)
  Rendered issues/_action_menu.html.erb (6.5ms)
  Rendered attachments/_links.html.erb (4.1ms)
  Rendered issue_relations/_form.html.erb (1.4ms)
  Rendered issues/_relations.html.erb (2.9ms)
  Rendered issues/_history.html.erb (5.6ms)
  Rendered issues/show.html.erb within layouts/base (52.3ms)
Completed 500 Internal Server Error in 149ms (ActiveRecord: 22.3ms)

ActionView::Template::Error (81581446479841676 is out of range for ActiveRecord::Type::Integer with limit 4):
     9: 
    10:     <% if journal.details.any? %>
    11:     <ul class="details">
    12:       <% details_to_strings(journal.visible_details).each do |string| %>
    13:        <li><%= string %></li>
    14:       <% end %>
    15:     </ul>
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/helpers/issues_helper.rb:427:in `show_detail'
  app/helpers/issues_helper.rb:345:in `block in details_to_strings'
  app/helpers/issues_helper.rb:331:in `each'
  app/helpers/issues_helper.rb:331:in `details_to_strings'
  app/views/issues/_history.html.erb:12:in `block in _app_views_issues__history_html_erb___4473561286554611286_70274107178120'
  app/views/issues/_history.html.erb:2:in `each'
  app/views/issues/_history.html.erb:2:in `_app_views_issues__history_html_erb___4473561286554611286_70274107178120'
  app/views/issues/show.html.erb:124:in `_app_views_issues_show_html_erb___2370284583150211555_70273934533180'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

VERSION

RAILS_ENV=production bin/about         

sh: 1: svn: not found
sh: 1: darcs: not found
sh: 1: hg: not found
sh: 1: cvs: not found
sh: 1: bzr: not found
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.0.0-p647 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  simple_author_change           0.1.2

Runnning on debian 8.3

**Comment by staskie** [comment]
To uninstall the plugin, simply remove it from your redmine/plugins folder.

**Comment by DanyK7** [comment]
Thanks for such a rapid response.
We deleted the plugin but had to re-run the bitnami "syncing"
e.g.:
$ cd installdir
$ ./use_redmine
$ cd apps/redmine/htdocs
$ bundle install --without development test postgresql sqlite
$ ruby bin/rake redmine:plugins RAILS_ENV=production

We can confirm that the behavior went back to normal, all issues are now displayable again.

Now that we can display the previously offending issues, we noticed something funny.
The crash was mentionning a problem converting to integer.
The integer that it was trying to convert was the filename attached to the issue !!!! 
i.e. the issues that ended up in error 500 had one attachment like this "81581446479841676.csv"

Attached is 2 print screens showing a stack trace and the number present is in the file name.
Certainly not coincidence !!!

Should you make the time to fix this we would be glad to test it again on our DEV system !
Thanks again.
![stracktrace](https://cloud.githubusercontent.com/assets/16959205/12682453/8696f4e6-c681-11e5-8b96-0e70dbc19e30.jpg)
![fileattached](https://cloud.githubusercontent.com/assets/16959205/12682454/869d8158-c681-11e5-95a9-20cbfb1f4ad4.jpg)

**Comment by mstroeve** [comment]
Exactly the same issue here with 3.2 and this plugin.

**Comment by gfrSE** [comment]
Any news?
